# Generated by Django 3.2.1 on 2021-05-05 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat_start', models.DecimalField(decimal_places=8, max_digits=9)),
                ('long_start', models.DecimalField(decimal_places=8, max_digits=9)),
                ('lat_end', models.DecimalField(decimal_places=8, max_digits=9)),
                ('long_end', models.DecimalField(decimal_places=8, max_digits=9)),
                ('total_psg', models.IntegerField()),
                ('status', models.CharField(max_length=200)),
                ('waktu', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat_pick', models.DecimalField(decimal_places=8, max_digits=9)),
                ('long_pick', models.DecimalField(decimal_places=8, max_digits=9)),
                ('lat_drop', models.DecimalField(decimal_places=8, max_digits=9)),
                ('long_drop', models.DecimalField(decimal_places=8, max_digits=9)),
                ('status', models.CharField(max_length=200)),
                ('waktu', models.DateTimeField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'request',
            },
        ),
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200)),
                ('fee', models.IntegerField()),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.request')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transaction',
            },
        ),
        migrations.CreateModel(
            name='finding_driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat_start_point', models.DecimalField(decimal_places=8, max_digits=9)),
                ('long_start_point', models.DecimalField(decimal_places=8, max_digits=9)),
                ('lat_end_point', models.DecimalField(decimal_places=8, max_digits=9)),
                ('long_end_point', models.DecimalField(decimal_places=8, max_digits=9)),
                ('waktu', models.DateTimeField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.order')),
            ],
            options={
                'db_table': 'finding_driver',
            },
        ),
    ]
